// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czffnavwikzjgdzquyrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6ZmZuYXZ3aWt6amdkenF1eXJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTI3MjIsImV4cCI6MjA2ODkyODcyMn0.EX8f_fwjxQtQuzUAl-iuy3Jz07lBlZ9H4p2JlzZZ8Y0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});